config/routes.rb
Rails.application.routes.draw do
  resources :profile, :trackers, :points

  # get 'history_show/:id' => 'history_show#shows', as: 'history_show'

  ActiveAdmin.routes(self)
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact',   to: 'static_pages#contact'

  get 'api_for_trackers/validate_tracker'
  get 'api_for_trackers/aaaa'
  get 'api_for_trackers/accept_message'
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  validates :imei_code, presence: true, imei: true, uniqueness: true

  validates :phone, presence: true

  belongs_to :user

  has_many :points

  belongs_to :protocol
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def index
  end

  def show
  	@tracker = Tracker.find(params[:id])
  	@points = @tracker.points

  	@hash = Gmaps4rails.build_markers(@points) do |tracker, marker|
  	  marker.lat tracker.latitude
  	  marker.lng tracker.longtitude
      marker.infowindow tracker.message
  	end
    p @hash
  end

  private

  def tracker_params
    params.require(:tracker).permit(:longtitude, :latitude, :tracker_id)
  end
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/trackers/index.html.erb
<h1>Trackers#index</h1>
<p>Find me in app/views/trackers/index.html.erb</p>

app/views/trackers/show.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDTY7KgMeYyIx9G1qP2sliMQJomWS3MYvs">  
</script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"> 
</script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'>
</script> 
 
<div class="container">
<div class="col-lg-12 col-sm-8">
  <div class="card hovercard">
    <div class="card-background">
      <img class="card-bkimg" alt="" src="/image/avatar.jpg">
      <!-- http://lorempixel.com/850/280/people/9/ -->
    </div>
    <div class="useravatar">
      <img alt="" src="/image/ava.png">
    </div>
    <div class="card-info"> <span class="card-title"><%= link_to current_user.email, profile_index_path %></span>
    </div>
  </div>
  <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <div class="hidden-xs">Online</div>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <div class="hidden-xs">Messages</div>
      </button>
    </div>
  </div>

 <div class="well">
    <div class="tab-content">
      <div class="tab-pane fade in active" id="tab1">
        <!-- <center> -->
          <div style='width: 800px;'>
            <div id="map" style='width: 1070px; height: 400px;'></div>
          </div>
        <!-- </center> -->
      </div>
          <% else %>
      <div class="tab-pane fade in" id="tab3">
        <table class="table">
          <tr>
          <td><h3>Отправлено</td>
          <td><h3>Сообщение</td> 
          </tr>
        <% @tracker.points.each do |point| %>
          <tr>
          <td><%= point.updated_at.strftime("%B %e, %Y at %I:%M %p") %></td> 
          <td><%= point.message %></td>
        </tr>
        <% end %>
        </table> 
      </div>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">

$(document).ready(function() {
  // })
  //   handler = Gmaps.build('Google');
  //   handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  //   markers = handler.addMarkers(<%=raw @hash.to_json %>);
  //   handler.bounds.extendWith(markers);
  //   handler.fitMapToBounds();
    
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  var origin      = new google.maps.LatLng(<%=raw @hash.first.to_json %>);
  var destination = new google.maps.LatLng(<%=raw @hash.last.to_json %>);
  var waypts = [];
  <% @hash.each do |point| %>
      waypts.push({
            location: new google.maps.LatLng(<%= point[:lat] %>, <%= point[:lng] %>),
            stopover: false
          });
  <% end %>
  
  

  
  var request = {
      origin:      origin,
      destination: destination,
      waypoints: waypts,
      optimizeWaypoints: true,
      travelMode:  google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
      
    }
  });
}

calcRoute();

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'map'}}, function(){
  directionsDisplay.setMap(handler.getMap());
  markers = handler.add(<%=raw @hash.to_json %>);
   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();

});
});

</script>

<!-- require 'enumerator'
a = (1..123).to_a
p a.each_slice(22).to_a
 -->